name: tfm
channels:
  - conda-forge
dependencies:
  - python=3.11.14
  - pip=25.2
  - numpy=2.3.3
  - pandas=2.3.3
  - matplotlib=3.10.6
  - seaborn=0.13.2
  - scikit-learn=1.7.2
  - requests=2.32.5
  - pathlib=1.0.1
  - jupyterlab=4.4.9
  - ipykernel=7.0.1
  - tqdm=4.67.1
  - python-dotenv=1.1.1
  - pip:
      - pydeseq2==0.5.2